server:
  port: 8083

spring:
  jersey:
    application-path: /
  datasource:
    url: jdbc:h2:mem:lra_order;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

inventory:
  base-url: http://localhost:8081

payment:
  base-url: http://localhost:8082

lra:
  coordinator:
    url: http://localhost:8080/lra-coordinator
  http:
    host: localhost
    port: 8080
    path: /lra-coordinator
